### ISSUE TITLE
SSH server start question 

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/openssh-portable#110]
Hello, this is just a question. I keep getting "sshd: no hostkeys available -- exiting." but I store my keys in ~/home/user/.ssh and I use this command to start the server "{opensshDir}./sshd -D -f {opensshDir}/sshd_config -o KexAlgorithms=kyber-512-sha256 -o HostKeyAlgorithms=ssh-dilithium3 -o PubkeyAcceptedKeyTypes=ssh-dilithium3 -h /home/user/.ssh/id-dilithium3"

Is there something that I am missing or I am doing wrong? As I am unable to figure out how to get it started.

**Comment by dstebila** [comment]
I don't recall ever trying to run it in that configuration.  To be clear you're trying to use the server (host) key from your home directory?

**Comment by prchander** [comment]
Yes. Should I move them to regress?

**Comment by baentsch** [comment]
> I am unable to figure out how to get it started.

Can you please post the output you're getting? A `mv` to regress doesn't sound like a good solution. Edit/additional question: Did you build oqs-openssh using the build script or did you pass different parameters to `./configure`? If so, which? Oh, and how did you create your host key file: Are you certain it is correct?

**Comment by prchander** [comment]
I followed the script and no additional parameters were passed to ./configure. 

The following script was used to create the keys 
./ssh-keygen -t ssh-dilithium3
This by default saves it to .ssh

**I wrote the server code in a python script** 
pi@pi:~/openssh/code$ python3 server.py 
Unable to load host key: /home/pi/.ssh/id-dilithium3
sshd: no hostkeys available -- exiting.

**Comment by baentsch** [comment]
Are you using the (host key file) name "id_dilithium3" (underscore: keygen-default) or "id-dilithium3" (hypen/dash: Wouldn't be found)?

**Comment by prchander** [comment]
Just caught that error and corrected the python script. Unfortunately, I am getting additional errors: 

**Modified code:**
{opensshDir}./sshd -D -f {opensshDir}/sshd_config -o KexAlgorithms=kyber-512-sha256 -o HostKeyAlgorithms=ssh_dilithium3 -o PubkeyAcceptedKeyTypes=ssh_dilithium3 -h /home/pi/.ssh/ssh_dilithium3

pi@pi:~/openssh/code$ python3 server.py 

command-line line 0: Bad key types 'ssh_dilithium3'.

**Comment by baentsch** [comment]
Same question (again :-) More seriously: You may want to check the permissible key type names (e.g., in `sshkey.c`). Edit: No, I have no clue why the types have a dash and the files an underscore... Maybe something historical (?)

**Comment by prchander** [comment]
Probably something historical with file names. I got everything fixed and just wondering what the server is supposed to do if it accepts everything. Currently I have no errors, but I expected the server to be in a loop searching for connections:

pi@pi:~/openssh/code$ python3 server.py 


pi@pi:~/openssh/code$

**Comment by baentsch** [comment]
I don't recall any file ''server.py" to be part of our code base, so would you object to closing this issue? Or is there a concrete question related to oqs-openssh?

**Comment by prchander** [comment]
I created the server.py code just to make writing the script easier. The python script contains this: 

{opensshDir}./sshd -D -f {opensshDir}/sshd_config -o KexAlgorithms=kyber-512-sha256 -o HostKeyAlgorithms=ssh-dilithium3 -o PubkeyAcceptedKeyTypes=ssh-dilithium3 -h /home/pi/.ssh/id_dilithium3

my question was that running the server script does not result with a loop like with TCP/TLS with OpenSSL. Just wondering if this is normal behavior. 

pi@pi:~/openssh/code$ python3 server.py 


pi@pi:~/openssh/code$

**Comment by baentsch** [comment]
Again, I've got to ask that you post the (also error) output of `sshd`. Without that I can't comment (and don't want to guess -- although I'm already now pretty certain it's a port permission error).

**Comment by baentsch** [comment]
Closing (probable local port permission error).
