### ISSUE TITLE
Drop support for v7.x branches

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/openssh-portable#115]
To reduce the number of code versions to be supported in this project, [it seems to be possible to use openssh v8 for libssh testing](https://github.com/open-quantum-safe/libssh/issues/5) 

-> Doable & sensible?

**Comment by kevinmkane** [comment]
open-quantum-safe/libssh#6 was merged today. That is my update to the libssh implementation to interoperate with the OQS-OpenSSH v8 branch, so the v7 branch should no longer be needed there.

**Comment by baentsch** [comment]
Thanks, @kevinmkane ! Before closing this for good, can I ask whether it'd be OK for you to drop the code version "tiedowns" in `libssh` testing for [openssh](https://github.com/open-quantum-safe/libssh/blob/5f0bc395e78dca23e0ba32b38d946cdbc8fd1d08/.github/workflows/ci.yml#L30) and [liboqs](https://github.com/open-quantum-safe/libssh/blob/5f0bc395e78dca23e0ba32b38d946cdbc8fd1d08/.github/workflows/ci.yml#L23) -- or replace `ref` with `OQS-v8` and `main` respectively)? This way regular CI on `libssh` would alert us of (undesired) inconsistencies creeping in over time in those packages.

**Comment by kevinmkane** [comment]
Yes, I'm fine with that. I'll maintain a note in the README to list the last known good revisions of each, but will default to building against the latest versions in the instructions and CI.

I don't currently have any nightly build jobs scheduled; I only have the job that runs when a PR is opened. Should I look into adding a nightly job so we find new build breaks quickly? Now that the v8 update is done I don't expect any changes for a while.

**Comment by baentsch** [comment]
> Should I look into adding a nightly job so we find new build breaks quickly?

I'd say that would be very sensible.

**Comment by dstebila** [comment]
The alternative to a nightly job in libssh would be to have an upstream job trigger jobs in libssh. But since there are multiple potential sources of upstream triggers (liboqs, OQS-OpenSSH) it is probably just easier to do a nightly job here.

As for dropping support for v7, yes, I think that's fine. We can leave the branch, just put a note in the README on that branch indicating it is no longer supported/updated, and that people should use the v8 branch.

**Comment by kevinmkane** [comment]
open-quantum-safe/libssh#9

**Comment by baentsch** [comment]
Thanks again!
