### ISSUE TITLE
Wireguard support?

### ISSUE THREAD

**Issue by zt3ph4n** [open-quantum-safe/openssh-portable#116]
Would it be possible to use the liboqs and thus the new algo's in Wireguard?
I'm not a coder myself, thou i'd really love to see a "OQS-Wireguard" fork, if not too much work?
(Don't wanna use M$ 'PQ-VPN' - lack of trust, open-source or not.)

Another OT-q; which one is the safest (toughest) of the liboqs algo's & which one is the speediest?
Read somewhere 'Picnic'-algo is fast & secure against quantum.

Why i ask is because running a VPS with a private VPN on Debian, so suggestions is very welcome.
Also, could you describe what to do to encrypt filesystem w/ the pq-ciphers?

Thank you a bunch for your work - amazing truly!
Kudoz for all work you've done! <3

Best regards/
Z

**Comment by dstebila** [comment]
> Would it be possible to use the liboqs and thus the new algo's in Wireguard? I'm not a coder myself, thou i'd really love to see a "OQS-Wireguard" fork, if not too much work? (Don't wanna use M$ 'PQ-VPN' - lack of trust, open-source or not.)

There's been some research on adding post-quantum algorithms to Wireguard, see https://eprint.iacr.org/2020/379.pdf.  Since that's already underway, we don't have plans to specifically connect OQS with Wireguard in this project.

> Another OT-q; which one is the safest (toughest) of the liboqs algo's & which one is the speediest? Read somewhere 'Picnic'-algo is fast & secure against quantum.

There's no simple answer to that.  I suggest waiting for the forthcoming selections by NIST to help narrow things down.

> Why i ask is because running a VPS with a private VPN on Debian, so suggestions is very welcome. Also, could you describe what to do to encrypt filesystem w/ the pq-ciphers?

Filesystem encryption generally uses symmetric, rather than public key, algorithms.

**Comment by zt3ph4n** [comment]
> > Would it be possible to use the liboqs and thus the new algo's in Wireguard? I'm not a coder myself, >thou i'd really love to see a "OQS-Wireguard" fork, if not too much work? (Don't wanna use M$ 'PQ->VPN' - lack of trust, open-source or not.)
> 
> There's been some research on adding post-quantum algorithms to Wireguard, see >https://eprint.iacr.org/2020/379.pdf. Since that's already underway, we don't have plans to specifically >connect OQS with Wireguard in this project.

> > Another OT-q; which one is the safest (toughest) of the liboqs algo's & which one is the speediest? Read somewhere 'Picnic'-algo is fast & secure against quantum.
> 
> There's no simple answer to that. I suggest waiting for the forthcoming selections by NIST to help narrow things down.
> 
> > Why i ask is because running a VPS with a private VPN on Debian, so suggestions is very welcome. >Also, could you describe what to do to encrypt filesystem w/ the pq-ciphers?
> 
> Filesystem encryption generally uses symmetric, rather than public key, algorithms.
>Aha, i see. Did'nt deepen in research in every algo of the pq-ciphers, but that clears some other >questions up too.

Okay , i see, thanks for the url!

**Comment by z-ph0ria** [comment]
https://0bin.net/paste/e8lygMN1#THhfTvUFFF2syYtE0rpaSK0uCiKDSfhDR6V517GcKFm

This is me running oqs-tests/run_tests.sh gives me.
