### ISSUE TITLE
Update to latest OpenSSH? 

### ISSUE THREAD

**Issue by zt3ph4n** [open-quantum-safe/openssh-portable#117]
Just a q, if you're going to upgrade main OpenSSH to latest (8.8p1)? - else i go with this one that you got, 8.4p1...

Best regards!

**Comment by baentsch** [comment]
We don't have immediate plans to do such update. If you know of (and/or need) specific new 8.8 features, please let us know so we can re-prioritize.

**Comment by zt3ph4n** [comment]
Because there are security-fixes & omitting the rsa (sha1) completely etc.?
Or maybe you got it covered?
Just asking...

**Comment by christianpaquin** [comment]
Started this, but ran into merge issues that prevented the project compilation. OpenSSH released yet another version, [V_8_9_P1](https://github.com/openssh/openssh-portable/tree/V_8_9_P1), which will be the new target.
