### ISSUE TITLE
Unable to compile under Debian 11

### ISSUE THREAD

**Issue by zt3ph4n** [open-quantum-safe/openssh-portable#118]
I get errors such as these, thou i've got OpenSSL 1.1.1m (your fork) and libqos installed.
See attached screenshot;
[Screenshot of error while compiling](https://delafil.se/858f978605ea4ec8/Screenshot_20220201-182113704.jpg) 

Thx f any help!
/z

**Comment by baentsch** [comment]
I fail to see in this screenshot what _caused_ the compiler terminations shown: There must have been an initial error leading to the termination of the compiler runs as shown in the screenshot. Please paste the logfile: Much better to review than a screenshot...

**Comment by zt3ph4n** [comment]
This is a link to what my log spitted out upon running oqs-scripts/build_openssh.sh;
https://0bin.net/paste/L6+kv8ce#YX3h8SLrwK5PAw8hEQ24YcTCplKsYrh+u38enPLPswo
Noticed there were errors & must adhere to the compile-failure. 
*Sigh*

**Comment by zt3ph4n** [comment]
https://0bin.net/paste/e8lygMN1#THhfTvUFFF2syYtE0rpaSK0uCiKDSfhDR6V517GcKFm

This is what oqs-template/run_tests.sh gives.

**Comment by zt3ph4n** [comment]
> I fail to see in this screenshot what _caused_ the compiler terminations shown: There must have been an initial error leading to the termination of the compiler runs as shown in the screenshot. Please paste the logfile: Much better to review than a screenshot...

If you have any insight what i should do, please give me any advice,
Thanx in advance!
Regards,
z

**Comment by baentsch** [comment]
> This is what oqs-template/run_tests.sh gives.

This link does not work.
