### ISSUE TITLE
Openssh release any time soon?

### ISSUE THREAD

**Issue by vt-alt** [open-quantum-safe/openssh-portable#127]
I thought you will release new OQS openssh together with liboqs but you didn't. Will you release OQS openssh any time soon or we should not wait for it?

**Comment by baentsch** [comment]
If no-one else volunteers (?), I'll release it before the end of this week

**Comment by vt-alt** [comment]
Ah. Thanks for the info!

**Comment by christianpaquin** [comment]
> If no-one else volunteers (?), I'll release it before the end of this week

Thanks @baentsch; out again this week, then out of vacation for a while :)

**Comment by vt-alt** [comment]
Thanks for the release!
