### ISSUE TITLE
Regression tests fail

### ISSUE THREAD

**Issue by himsen** [open-quantum-safe/openssh-portable#13]
Issue first reported in PR #12 

A fresh checkout - using the master branch of libOQS - fails the OpenSSH regression tests reporting random looking memory corruption errors. A manual run also does not succeed.

I tried annotating with a few printf's and it seems that the kem structure returned from libOQS contains obviously wrong values. 

```
Hybrid using oqs method: DEFAULT
In oqs_client_gen()
oqs_kem->length_shared_secret: 94821083628384
```

I need to investigate this further. But this should block any further work on this fork.

**Comment by himsen** [comment]
This problem will probably go away after discovering the reason for open-quantum-safe/liboqs#420

**Comment by dstebila** [comment]
Resolved by discussion in open-quantum-safe/liboqs#420.
