### ISSUE TITLE
OQS SSH Key Signing for PKI fails with quantum-resistant algorithms

### ISSUE THREAD

**Issue by isaleh-sb** [open-quantum-safe/openssh-portable#154]
I'm trying to setup a PKI with OQS OpenSSH similar to how it's described here https://hosakacorp.net/p/ssh-pki.html and encountering errors when attempting to upgrade the key to a certificate for QRC algorithms:
`Could not upgrade key ssh_ca.test.com.pub to certificate: invalid argument`

I'm wondering, is this is a bug or a feature that is known to not be supported as of now? If it is something known, are there plans to eventually support SSH PKI for quantum resistant algorithms in this project? Thanks! 😄 

Steps to reproduce:
```
ssh-keygen -t ssh-dilithium5 -f ssh_ca.test.com
ssh-keygen -s ssh_ca.test.com -h -I "ca.test.com" -n "ca.test.com,server" -V "-1m:+520w" -z 1 ssh_ca.test.com.pub
Could not upgrade key ssh_ca.test.com.pub to certificate: invalid argument
```
Classical working fine with same build:
```
ssh-keygen -t ssh-rsa -b 4096 -f ssh_ca.test.com
ssh-keygen -s ssh_ca.test.com -h -I "ca.test.com" -n "ca.test.com,server" -V "-1m:+520w" -z 1 ssh_ca.test.com.pub
Signed host key ssh_ca.test.com-cert.pub: id "ca.test.com" serial 1 for ca.test.com,server valid from 2024-01-05T19:18:48 to 2033-12-23T19:19:48
```

**Comment by FS93** [comment]
As far as I see it, signing of certificates is currently only supported for those which contain public keys of the types listed in [`sshkey_to_certified`](https://github.com/open-quantum-safe/openssh/blob/OQS-v8/sshkey.c#L3429), i.e. **the signing of certificates with PQC public key types is not yet supported**. If one tries to sign a certificate containing a different key type, the error is raised [here](https://github.com/open-quantum-safe/openssh/blob/OQS-v8/ssh-keygen.c#L1966).

**Comment by baentsch** [comment]
Looks like a duplicate to #24.
