### ISSUE TITLE
Can't find LibOQS library

### ISSUE THREAD

**Issue by luis-at** [open-quantum-safe/openssh-portable#156]
Hi,
I'm following the instructions provided to build the project but, still, I always bump into the following error: configure: error: *** Can't find LibOQS library (see config.log for details) ***

This happens on the last step while running `sudo ./oqs-scripts/build_openssh.sh`.

I'm running Ubuntu 20.04.6 LTS (Focal Fossa). I cannot find any relevant information on the config.log file as suggested by the error. 

Has anyone faced the same issue?

Thanks in advance!

**Comment by luis-at** [comment]
Fixed by adding `-DBUILD_SHARED_LIBS=ON` to the cmake command on the `./oqs-scripts/build_liboqs.sh` file as suggested [here](https://stackoverflow.com/questions/72134508/looking-to-use-a-library-with-example-code-for-open-quantum-safe).

**Comment by baentsch** [comment]
Thanks for the report and the solution, @luis-at -- took this as the basis for #157. If you see value in this project, please let us know and possibly consider contributing via PR's in the future.
