### ISSUE TITLE
Add post-quantum signature-based authentication in SSH

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/openssh-portable#17]

**Comment by csosto-pk** [comment]
Good to see this Prof Stebila. Just curious, is the first PQ sig scheme supported going to be XMSS? 
I am guessing yes, judging from the code I see in the branch.

**Comment by himsen** [comment]
Hi. If you are referring to the XMSS scheme already in the OpenSSH-Portable repo, then this is a separate project, disjoint from the effort by OQS. That XMSS code is added by the OpenSSH developers.

The supported algorithms will most likely include all the signature schemes supported by libOQS.

**Comment by csosto-pk** [comment]
Got it. Thank for the quick response @himsen  , I appreciate it. 

I probably should not be asking this question in this repo, but liboqs seems to only include [picnic and qTesla currently](https://github.com/open-quantum-safe/liboqs/tree/master/src/sig). Are you aware if other sig algorithms coming soon in liboqs?

**Comment by himsen** [comment]
@dstebila would be the person to answer that :)

**Comment by christianpaquin** [comment]
I just noticed this issue! I hope my PR #22 doesn't conflict with some of your work in progress

**Comment by dstebila** [comment]
Fixed by #22
