### ISSUE TITLE
Algorithms disabled in liboqs should be disabled in OpenSSH.

### ISSUE THREAD

**Issue by xvzcf** [open-quantum-safe/openssh-portable#44]
When liboqs is built, autoconf outputs `config.h`, which contains preprocessor defines that state what algorithms are enabled at the variant level; for e.g.: if in the file we have
` ... `
 `#define OQS_ENABLE_SIG_qTESLA_I 1`
`/* #define OQS_ENABLE_SIG_qTESLA_III_size*/`
` ...`
this means `qTESLA_I` is enabled and `qTESLA_III_size` is not.

OpenSSH should also be able to enable and disable the use of these algorithms according to the `config.h` output.

At present in OpenSSH, we disable "by family", i.e. if even one of symbol of the set {`OQS_ENABLE_KEM_kyber_512`, `OQS_ENABLE_KEM_kyber_768`, `OQS_ENABLE_KEM_kyber_1024`} is not defined, then all of Kyber is disabled in OpenSSH.

**Comment by dstebila** [comment]
See https://github.com/open-quantum-safe/openssl/issues/122#issuecomment-536072028.

**Comment by dstebila** [comment]
Won't fix.
