### ISSUE TITLE
Update build documentation

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/openssh-portable#45]
The `README.md` build instructions differ from what we use in the `oqs_test/scripts/build_openssh.sh`. In particular, the ` --with-libs=-lm` param is missing, which caused a build failure on my system when trying to build following the README instructions.

We should review the documented steps to make sure they work.

**Comment by dstebila** [comment]
Fixed by 9bdff2d4543ec8c8494f63f910c2786c35e08edc.
