### ISSUE TITLE
make tests fails

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/openssh-portable#7]
When I run OQS-master on my Ubuntu VM, `make tests` fails.  The failure (see attached log) seems to not be connected with any of our changes.  Eric did some checking and also encountered failures during `make tests` when running various commits even before our changes.  So probably not our problem.  This issue is to record the issue, discuss, and decide if we want to do anything about it.

**Comment by dstebila** [comment]
[make_tests.log](https://github.com/open-quantum-safe/openssh-portable/files/2210627/make_tests.log)

**Comment by crockeea** [comment]
On Ubuntu 16.04, I get past the "sftp commands" tests, but get stuck on "forwarding.sh".

```
> make tests
...
run test forwarding.sh ...
failed copy of /bin/ls
cmp: EOF on ~/openssh-portable/regress
corrupted copy of /bin/ls
Exit request sent.
...
Exit request sent.
failed local and remote forwarding
Makefile:207: recipe for target 't-exec' failed
make[1]: *** [t-exec] Error 1
make[1]: Leaving directory '.../regress'
Makefile:582: recipe for target 'tests' failed
make: *** [tests] Error 2
```

This also appears to be unrelated to Torben's changes. I get the same error on the real openssh-portable repo, with the HEAD of master branch.

**Comment by dstebila** [comment]
Problem doesn't exist on some platforms (AmazonLinux, some Ubuntu) and even when it does occur seems to be unrelated to our changes.  Closing.
