### ISSUE TITLE
ssh-keygen generates P-256 keys for p384_rainbowiiicclassic and p521_rainbowvcclassic when referring to them by short name

### ISSUE THREAD

**Issue by kevinmkane** [open-quantum-safe/openssh-portable#73]
Keys of these two types generated by ssh-keygen cause ssh to complain "invalid format" when provided for client authentication. Keys for the pure-PQ versions of these algorithms work fine, as do keys for p256_rainbowiaclassic.

Setup for the experiment:

1. `ssh-keygen -t RAINBOWIACLASSIC -q -N "" -f id_rainbowiaclassic`
2. `ssh-keygen -t RAINBOWIIICCLASSIC -q -N "" -f id_rainbowiiicclassic`
3. `ssh-keygen -t RAINBOWVCCLASSIC -q -N "" -f id_rainbowvcclassic`
4. `ssh-keygen -t P256_RAINBOWIACLASSIC -q -N "" -f id_p256_rainbowiaclassic`
5. `ssh-keygen -t P384_RAINBOWIIICCLASSIC -q -N "" -f id_p384_rainbowiiicclassic`
6. `ssh-keygen -t P521_RAINBOWVCCLASSIC -q -N "" -f id_p521_rainbowvcclassic`
7. `cat id_*.pub >/tmp/authorized_keys`

OQS-OpenSSH is installed in ~/build/openssh. 

I first attempted this with liboqs built at the 0.4.0 tag (open-quantum-safe/liboqs@02fddd93) and openssh is built at "Added NTRU-Prime. #68" (0e49ae9c). I then attempted it with liboqs at its current tip "Sync with PQClean" (open-quantum-safe/liboqs@1ad950ac) and openssh at its current tip "Add HQC round 3" (0f0b045b). Both exhibited the same results given below.

Server command line: 
`~/build/openssh/sbin/sshd -d -d -d -p 1234 -f ~/build/openssh/sshd_config -o AuthorizedKeysFile=/tmp/authorized_keys -o PubkeyAcceptedKeyTypes=ssh-rainbowiaclassic,ssh-rainbowiiicclassic,ssh-rainbowvcclassic,ssh-p256-rainbowiaclassic,ssh-p384-rainbowiiicclassic,ssh-p521-rainbowvcclassic -o StrictModes=no -h ~/build/openssh/ssh_host_rsa_key`

Client command line (in directory where ssh-keygen outputs are present): 
`ssh -v -p 1234 127.0.0.1 -F ~/build/openssh/ssh_config -o PubkeyAcceptedKeyTypes=ssh-rainbowiaclassic,ssh-rainbowiiicclassic,ssh-rainbowvcclassic,ssh-p256-rainbowiaclassic,ssh-p384-rainbowiiicclassic,ssh-p521-rainbowvcclassic -o StrictHostKeyChecking=no -i ${KEY} ls` 
where `${KEY}` is one of: `./id_rainbowiaclassic` `./id_rainbowiiicclassic` `./id_rainbowvcclassic` `./id_p256_rainbowiaclassic` `./id_p384_rainbowiiicclassic` `./id_p521_rainbowvcclassic`

Expected results: key is accepted each time, and `ls` command is executed. In particular, note this snippet from the client debug output (output for p256_rainbowiaclassic shown):
```
debug1: Will attempt key: ./id_p256_rainbowiaclassic P256_RAINBOWIACLASSIC SHA256:71v0bzcaK8/AsUTOY3KNfsf3mqojjW0aawJM9ryZcJI explicit
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Offering public key: ./id_p256_rainbowiaclassic P256_RAINBOWIACLASSIC SHA256:71v0bzcaK8/AsUTOY3KNfsf3mqojjW0aawJM9ryZcJI explicit
debug1: Server accepts key: ./id_p256_rainbowiaclassic P256_RAINBOWIACLASSIC SHA256:71v0bzcaK8/AsUTOY3KNfsf3mqojjW0aawJM9ryZcJI explicit
debug1: Authentication succeeded (publickey).
Authenticated to 127.0.0.1 ([127.0.0.1]:1234).
```

Actual results for p384_rainbowiiicclassic and p521_rainbowvcclassic (output is for p521_rainbowvcclassic, but p384_rainbowiiiclassic exhibits the same behavior with just the filenames different):
```
debug1: Will attempt key: ./id_p521_rainbowvcclassic  explicit
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Trying private key: ./id_p521_rainbowvcclassic
Load key "./id_p521_rainbowvcclassic": invalid format
debug1: Next authentication method: keyboard-interactive
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: password
kkane@127.0.0.1's password: 
```

Interestingly, a hash fingerprint is shown for the key types that do work, but not for the ones that do not. There is also a noticeable delay of a few seconds after it prints `debug1: Trying private key: ./id_p521_rainbowvcclassic` which is a line that does not appear in the successful trace.

**Comment by dstebila** [comment]
Hi Kevin, this reminds me of the problems we encountered with Rainbow III and V in SSH that we reported in Table 2 and Section 4.2 of our [2019 paper on TLS and SSH integrations](https://eprint.iacr.org/2019/858).  At the time we didn't figure out how to get it working, and haven't made any progress since then.  At least as far as I can remember.  @xvzcf any other thoughts?

**Comment by kevinmkane** [comment]
This seems to happen while ssh is attempting to load the private key file, not send the public key over the network, though it's certainly possible it's running into some other size limit. I may poke at it a bit more, but thought I'd put the report out there in case something obvious occurred to you all. A file load problem seemed like it might (dare I dream) be more straightforward.

**Comment by xvzcf** [comment]
Most (but perhaps not all) issues in that paper should've been fixed in [this commit](https://github.com/open-quantum-safe/openssh/commit/b452beeb20f28b4e3af4b77c19855ed891a36ec8). I did have to increase size limits in various places (like [here](https://github.com/open-quantum-safe/openssh/commit/b452beeb20f28b4e3af4b77c19855ed891a36ec8#diff-4541d53042b064e61bbf4e8884081b586d8ca22769f101f3136b27418a96dd07R103) for example), but I might've missed a spot.

With respect to the delay in loading the private key file, it might be that the file is being processed 1 byte at a time. That resulted in huge delays when writing generated Rainbow keys out to a file, and was improved [here](https://github.com/open-quantum-safe/openssh/commit/b452beeb20f28b4e3af4b77c19855ed891a36ec8#diff-911b87e474316fdc8c48074a84d40562d1b0e7f06fa587d9b8f13926c539d81cR4068) by writing out to the file in 70-byte bursts.

**Comment by xvzcf** [comment]
At any rate, I'll try looking into this in a week or two if there isn't a solution by then.

**Comment by kevinmkane** [comment]
ssh-keygen is generating P-256 keys for these two schemes when ssh-keygen is given their "short names" as the -t parameter (which is by far the norm). When these keys later get loaded, the curve nid doesn't match anything in the keytypes table, and so the keys are dismissed as unknown.

#74 corrects this behavior by always coercing the required number of classical bits to the correct number when choosing one of these hybrids that refers to a specific elliptic curve.

**Comment by xvzcf** [comment]
Closed by https://github.com/open-quantum-safe/openssh/pull/74
