### ISSUE TITLE
Template casing error results in malformed name for SIKE_P434_COMPRESSED algorithm.

### ISSUE THREAD

**Issue by ljoy913** [open-quantum-safe/openssh-portable#75]
openssh/oqs-template/**generate.yml**

   NAME: "SIKE_P434_COMPRESSED"

'NAME' should be lowercase, as the other instances. When the templates are generated, the name for this algorithm is malformed.

For example, in myproposal.h:

#define KEX_PQ_METHOD_SIKE \
    PQ_OQS_KEX_METHOD("sike-p434-sha384") \
    PQ_OQS_KEX_METHOD("sike-p503-sha384") \
    PQ_OQS_KEX_METHOD("sike-p610-sha384") \
    PQ_OQS_KEX_METHOD("sike-p751-sha384") \
    PQ_OQS_KEX_METHOD("-sha384") \   <------------------------------------------ here
    PQ_OQS_KEX_METHOD("sike-p503-compressed-sha384") \
    PQ_OQS_KEX_METHOD("sike-p610-compressed-sha384") \
    PQ_OQS_KEX_METHOD("sike-p751-compressed-sha384")

Using lowercase 'name' and regenerating the templates fixes this issue.

**Comment by dstebila** [comment]
Can you see if #76 fixes it for you?

**Comment by dstebila** [comment]
@xvzcf Any idea why tests didn't fail for this?

**Comment by xvzcf** [comment]
Will investigate.
