### ISSUE TITLE
Minor mistake in README.md

### ISSUE THREAD

**Issue by xykro** [open-quantum-safe/openssh-portable#83]
The information about [which algorithms are enabled by default](https://github.com/open-quantum-safe/openssh#digital-signature) is slightly wrong. It is mentioned that 

> **all** Rainbow variants are enabled by default

where in reality only the classical variants are actually enabled (referring to [oqs-template/generate.yml](https://github.com/open-quantum-safe/openssh/blob/OQS-master/oqs-template/generate.yml)).

**Comment by baentsch** [comment]
Thanks for this report. You're right and we fix it with #84.
