### ISSUE TITLE
Make OQS_v8 the default branch in this repo

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/openssh-portable#92]

**Comment by baentsch** [comment]
@dstebila @xvzcf : What'd be needed to do this switch?

**Comment by dstebila** [comment]
> @dstebila @xvzcf : What'd be needed to do this switch?

Just the go ahead from whoever has an opinion.  I can make the switch in the Github configuration easily.

**Comment by baentsch** [comment]
My opinion would be to do it as and when https://github.com/open-quantum-safe/oqs-demos/pull/88 passes CI.

**Comment by dstebila** [comment]
> My opinion would be to do it as and when [open-quantum-safe/oqs-demos#88](https://github.com/open-quantum-safe/oqs-demos/pull/88) passes CI.

Okay, I'll watch for that.

**Comment by dstebila** [comment]
Done. 

Shall I rename OQS-master to OQS-v7 as well, or does anything depend on it still being called OQS-master?

**Comment by baentsch** [comment]
> Done.

Thanks.

> Shall I rename OQS-master to OQS-v7 as well, or does anything depend on it still being called OQS-master?

Well, old build scripts depend on that (should someone want to re-build v7 stuff). Generally I don't see value in re-naming it -- unless we want it to eventually refer to the true "master" (err, "main").

**Comment by dstebila** [comment]
> > Shall I rename OQS-master to OQS-v7 as well, or does anything depend on it still being called OQS-master?
> 
> Well, old build scripts depend on that (should someone want to re-build v7 stuff). Generally I don't see value in re-naming it -- unless we want it to eventually refer to the true "master" (err, "main").

Okay we'll leave it.
