### ISSUE TITLE
Cygwin support 

### ISSUE THREAD

**Issue by huaraz** [open-quantum-safe/openssh-portable#93]
Is it possible to add cygwin support ?  I get asm compile errors e.g. 

$ ninja
[18/1508] Building ASM object src/kem/...les/bike1_l1_fo.dir/additional/red.S.o
FAILED: src/kem/bike/CMakeFiles/bike1_l1_fo.dir/additional/red.S.o
/usr/bin/cc -DAVX2 -DFUNC_PREFIX=OQS_KEM_bike1_l1_fo -DLEVEL=1 -Iinclude -I/usr/include -fPIC -march=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -Wno-maybe-uninitialized -mavx2 -include /home/moelma/git/liboqs/src/kem/bike/functions_renaming.h -MD -MT src/kem/bike/CMakeFiles/bike1_l1_fo.dir/additional/red.S.o -MF src/kem/bike/CMakeFiles/bike1_l1_fo.dir/additional/red.S.o.d -o src/kem/bike/CMakeFiles/bike1_l1_fo.dir/additional/red.S.o -c ../src/kem/bike/additional/red.S
../src/kem/bike/additional/red.S: Assembler messages:
../src/kem/bike/additional/red.S:19: Error: unknown pseudo-op: `.hidden'
../src/kem/bike/additional/red.S:21: Warning: .type pseudo-op used outside of .def/.endef: ignored.
../src/kem/bike/additional/red.S:21: Error: junk at end of line, first unrecognized character is `O'
../src/kem/bike/additional/red.S:58: Warning: .size pseudo-op used outside of .def/.endef: ignored.
../src/kem/bike/additional/red.S:58: Error: junk at end of line, first unrecognized character is `O'
[19/1508] Building ASM object src/kem/.../bike1_l1_fo.dir/additional/gf_mul.S.o

I also saw the following:

FAILED: tests/kat_sig.exe
: && /usr/bin/cc  -Wl,--enable-auto-import   -Wl,--stack,16777216 tests/CMakeFiles/kat_sig.dir/kat_sig.c.o -o tests/kat_sig.exe -Wl,--out-implib,tests/libkat_sig.dll.a -Wl,--major-image-version,0,--minor-image-version,0  lib/liboqs.a  -lm  /usr/lib/libcrypto.dll.a && :
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3.c.o):xkcp_sha3.c:(.text$Keccak_Dispatch+0x47): undefined reference to `KeccakP1600_Initialize'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3.c.o):xkcp_sha3.c:(.rdata$.refptr.KeccakP1600_ExtractBytes[.refptr.KeccakP1600_ExtractBytes]+0x0): undefined reference to `KeccakP1600_ExtractBytes'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3.c.o):xkcp_sha3.c:(.rdata$.refptr.KeccakP1600_Permute_24rounds[.refptr.KeccakP1600_Permute_24rounds]+0x0): undefined reference to `KeccakP1600_Permute_24rounds'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3.c.o):xkcp_sha3.c:(.rdata$.refptr.KeccakP1600_AddBytes[.refptr.KeccakP1600_AddBytes]+0x0): undefined reference to `KeccakP1600_AddBytes'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3.c.o):xkcp_sha3.c:(.rdata$.refptr.KeccakP1600_AddByte[.refptr.KeccakP1600_AddByte]+0x0): undefined reference to `KeccakP1600_AddByte'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3.c.o):xkcp_sha3.c:(.rdata$.refptr.KeccakP1600_Initialize[.refptr.KeccakP1600_Initialize]+0x0): undefined reference to `KeccakP1600_Initialize'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3x4.c.o):xkcp_sha3x4.c:(.text$Keccak_X4_Dispatch+0x47): undefined reference to `KeccakP1600times4_InitializeAll'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3x4.c.o):xkcp_sha3x4.c:(.rdata$.refptr.KeccakP1600times4_ExtractBytes[.refptr.KeccakP1600times4_ExtractBytes]+0x0): undefined reference to `KeccakP1600times4_ExtractBytes'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3x4.c.o):xkcp_sha3x4.c:(.rdata$.refptr.KeccakP1600times4_PermuteAll_24rounds[.refptr.KeccakP1600times4_PermuteAll_24rounds]+0x0): undefined reference to `KeccakP1600times4_PermuteAll_24rounds'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3x4.c.o):xkcp_sha3x4.c:(.rdata$.refptr.KeccakP1600times4_AddBytes[.refptr.KeccakP1600times4_AddBytes]+0x0): undefined reference to `KeccakP1600times4_AddBytes'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3x4.c.o):xkcp_sha3x4.c:(.rdata$.refptr.KeccakP1600times4_AddByte[.refptr.KeccakP1600times4_AddByte]+0x0): undefined reference to `KeccakP1600times4_AddByte'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3x4.c.o):xkcp_sha3x4.c:(.rdata$.refptr.KeccakP1600times4_InitializeAll[.refptr.KeccakP1600times4_InitializeAll]+0x0): undefined reference to `KeccakP1600times4_InitializeAll'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Thank you
Markus

**Comment by baentsch** [comment]
Thanks for your interest in our project as well as the suggestion. Is this more of a [liboqs issue](https://github.com/open-quantum-safe/liboqs/issues)? I don't have a cygwin environment at my disposal, so pardon the question: Can you build and run `ninja run_tests` using cygwin OK in that project?

**Comment by huaraz** [comment]
Oh sorry, you are right. I'll post it  under liboqs.

Markus
