### ISSUE TITLE
Windows native version

### ISSUE THREAD

**Issue by huaraz** [open-quantum-safe/openssh-portable#94]
Would you know if the "native" Windows 10 version of openssh build with MSVC ?  Would it be possible to have oqs-openssh also build with MSVC ?

Thank you
Markus

**Comment by baentsch** [comment]
Hi Markus, courtesy @christianpaquin here's a pointer as to how to build openssh for "native Windows" (using Powershell and MSVC): https://github.com/PowerShell/openssh-portable/tree/latestw_all/contrib/win32/openssh

We have not tried this ourselves but would be glad to hear about your experiences (as well as possible adaptations needed).

**Comment by baentsch** [comment]
Assuming issue to be closed courtesy the link above.
