### ISSUE TITLE
Cygwin install issue

### ISSUE THREAD

**Issue by huaraz** [open-quantum-safe/openssh-portable#95]
Hi
 
   I used the updated liboqs, but I get still the below install error. i.e. PICNIC related keys can not be created.

/usr/local/ssh_config already exists, install will not overwrite
/usr/local/sshd_config already exists, install will not overwrite
/usr/local/moduli already exists, install will not overwrite
ssh-keygen: generating new host keys: PICNIC_L1FULL PICNIC3_L1 RAINBOW_V_CLASSIC /bin/sh: line 2: 26256 Segmentation fault      (core dumped) ./ssh-keygen -A
make: *** [Makefile:391: host-key] Error 139

ssh-keygen: generating new host keys: RSA3072_PICNIC_L1FULL RSA3072_PICNIC3_L1 P256_PICNIC_L1FULL P256_PICNIC3_L1 P521_RAINBOW_V_CLASSIC /bin/sh: line 2: 26379 Segmentation fault      (core dumped) ./ssh-keygen -A

  I can comment them out of ssh-keygen.c and can install the package/
. 

Thank you
Markus

**Comment by baentsch** [comment]
Hi Markus, is it only Picnic keys that fail or all PQ-signature algorithms (say, dilithium3, too)?

**Comment by huaraz** [comment]
These 8 fail:

PICNIC_L1FULL
PICNIC3_L1
RAINBOW_V_CLASSIC
RSA3072_PICNIC_L1FULL
RSA3072_PICNIC3_L1
P256_PICNIC_L1FULL
P256_PICNIC3_L1
P521_RAINBOW_V_CLASSIC

Markus

**Comment by baentsch** [comment]
Thanks for this information. Do you have urgent need for these algorithms or can you make do for now with the rest? We'd prefer to look into this issue in the new code base (after #91 is resolved): OK for you?

**Comment by huaraz** [comment]
Hi Michael,

  There is no urgency. It is just a feedback which might help improve it.

Markus

**Comment by baentsch** [comment]
Thanks again. FYI, running on PR-branch `mb-v8test` the problem you describe does not seem to happen (activating some more algs for test purposes -- all using cygwin):
```
ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519 OQS_DEFAULT PICNIC_L1_FS PICNIC_L1_UR PICNIC_L1_FULL PICNIC_L3_FS PICNIC_L3_FULL PICNIC_L5_FS PICNIC_L5_UR PICNIC_L5_FULL RAINBOW_I_CLASSIC RSA3072_OQS_DEFAULT RSA3072_PICNIC_L1_FS RSA3072_PICNIC_L1_UR RSA3072_PICNIC_L1_FULL RSA3072_RAINBOW_I_CLASSIC ECDSA_NISTP256_OQS_DEFAULT ECDSA_NISTP256_PICNIC_L1_FS ECDSA_NISTP256_PICNIC_L1_UR ECDSA_NISTP256_PICNIC_L1_FULL ECDSA_NISTP384_PICNIC_L3_FS ECDSA_NISTP384_PICNIC_L3_FULL ECDSA_NISTP521_PICNIC_L5_FS ECDSA_NISTP521_PICNIC_L5_UR ECDSA_NISTP521_PICNIC_L5_FULL ECDSA_NISTP256_RAINBOW_I_CLASSIC
```
--> Will probably now create a cygwin-based CI environment for `oqs-openssh (v8.4)` to catch such things going forward. Sufficient for you? If so, you'll be notified when this has landed.

**Comment by baentsch** [comment]
If you have time, could you please check branch [OQS-v8](https://github.com/open-quantum-safe/openssh/tree/OQS-v8) as to whether this "behaves better" wrt to this issue and your use case? We'll soon make it the new "main" branch, deprecating support for opensshv7. Thanks in advance for your feedback.

**Comment by huaraz** [comment]
Hi Michael,

  This branch worked w/o issues.

Markus

**Comment by baentsch** [comment]
Thanks for this confirmation. So we'll close this issue when #92 closes.
